### ISSUE TITLE
layers from manifest don't match image configuration

### ISSUE THREAD

**Issue by tchelle** [webdetails/cbf2#4]
Thank you for this great docker bundle.  A few weeks back it started failing to pull down. My original guess was that 1 of the layers that "Already exists" was the problem. I also received the "layers from manifest don't match image configuration" message after removing all images and containers. Below is a recent attempt with some layers which already exist

OS= Mac OSX 10.10.5
Docker=Version 1.12.0-rc2-beta17 (build: 9779)

$ docker pull pentaho/biserver
Using default tag: latest
latest: Pulling from pentaho/biserver
6ffe5d2d6a97: Already exists 
f4e00f994fd4: Already exists 
e99f3d1fc87b: Already exists 
a3ed95caeb02: Pull complete 
b3598f593928: Pull complete 
02c26cc5a15d: Pull complete 
99eaa6b2bdf3: Pull complete 
04af1d27b3f2: Pull complete 
e994be9c77bf: Pull complete 
a8d0724e4356: Pull complete 
f7509f7e0b67: Pull complete 
b64162ceb76a: Pull complete 
bb170c8d35f6: Pull complete 
ed31c6d56223: Pull complete 
9d0bac0300fc: Pull complete 
8434f018e234: Pull complete 
layers from manifest don't match image configuration

Regards

**Comment by tchelle** [comment]
Hello
since the above post I uninstalled docker for mac and reinstalled to make sure I had the latest version on July 25 (yes I know this is Beta and may not be worth the hassle but it doesn't hurt to post this). I received the same error

$ docker pull pentaho/biserver
Using default tag: latest
latest: Pulling from pentaho/biserver
6ffe5d2d6a97: Pull complete 
f4e00f994fd4: Pull complete 
e99f3d1fc87b: Pull complete 
a3ed95caeb02: Pull complete 
b3598f593928: Pull complete 
02c26cc5a15d: Pull complete 
99eaa6b2bdf3: Pull complete 
04af1d27b3f2: Pull complete 
e994be9c77bf: Pull complete 
a8d0724e4356: Pull complete 
f7509f7e0b67: Pull complete 
b64162ceb76a: Pull complete 
bb170c8d35f6: Pull complete 
ed31c6d56223: Pull complete 
9d0bac0300fc: Pull complete 
8434f018e234: Pull complete 
layers from manifest don't match image configuration

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: 6AWL:HBSX:VNX2:MXHR:X5P6:3JNQ:TM4R:6EJP:JXHQ:777C:EDRJ:TVKX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2016-07-25T18:08:36.048258124Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Comment by Max-Sundar-vine** [comment]
I ran into the same problem :(

]$ docker pull pentaho/biserver
Using default tag: latest
latest: Pulling from pentaho/biserver
6ffe5d2d6a97: Pull complete 
f4e00f994fd4: Pull complete 
e99f3d1fc87b: Pull complete 
a3ed95caeb02: Pull complete 
b3598f593928: Pull complete 
02c26cc5a15d: Pull complete 
99eaa6b2bdf3: Pull complete 
04af1d27b3f2: Pull complete 
e994be9c77bf: Pull complete 
a8d0724e4356: Pull complete 
f7509f7e0b67: Pull complete 
b64162ceb76a: Pull complete 
bb170c8d35f6: Pull complete 
ed31c6d56223: Pull complete 
9d0bac0300fc: Pull complete 
8434f018e234: Pull complete 
layers from manifest don't match image configuration
